<div id="footerposition">

	<div id="footercontent">
		<div id="footer1">
			<h1 id="footer1content1">Mount Doug Peer Tutoring</h1>
			<h5 id="footer1content2">&copy; Mount Douglas Secondary School 2023</h5>
		</div>
		<div id="footer2">
			<h1>About the Program</h1>
			<p>
				Mount Douglas' peer tutors are available to help you with all of your academic needs and assist with
				homework, test preparation and studying skills. We offer after school drop-in sessions, tutor pairings,
				and math support; Monday to Friday.
				<br><br>
				Peer tutoring is proven to enhance learning and helps numerous Mount Douglas students every day, so
				don't hesitate to stop by for any academic assistance!
			<p>
		</div>
		<div id="footer3">
			<h1>Links</h1>
			<ul id="footerlist">
				<li>
					<a href="?page=1">View Peer Tutor Profiles</a>
				</li>

				<li>
					<a href="?page=2">Become A Peer Tutor</a>
				</li>

				<li>
					<a href="?page=3">Book A Peer Tutor Session</a>
				</li>

				<li>
					<a href="?delete=true">Reset Profile Image Gallery</a>
				</li>

				<li>
					<a href="downloadall.php" download>Download All Profile Images</a>
				</li>
			</ul>

		</div>
	</div>

</div>

</body>

</html>